cecho("\n<cyan>╔════════════════════════════════════════════════════════════════╗<reset>\n")
cecho("<cyan>║<reset>                      <white>ShipDB - Help Menu<reset>                        <cyan>║<reset>\n")
cecho("<cyan>╠════════════════════════════════════════════════════════════════╣<reset>\n")
cecho("<cyan>║<reset> <yellow>Window Commands:<reset>                                               <cyan>║<reset>\n")
cecho("<cyan>║<reset>   <white>showships<reset>              Show the ship database window         <cyan>║<reset>\n")
cecho("<cyan>║<reset>   <white>hideships<reset>              Hide the ship database window         <cyan>║<reset>\n")
cecho("<cyan>║<reset>                                                                <cyan>║<reset>\n")
cecho("<cyan>║<reset> <yellow>Filter & Search Commands:<reset>                                      <cyan>║<reset>\n")
cecho("<cyan>║<reset>   <white>shipdb filter <text><reset>   Filter ships/records by any text      <cyan>║<reset>\n")
cecho("<cyan>║<reset>   <white>shipdb clear<reset>           Clear all active filters              <cyan>║<reset>\n")
cecho("<cyan>║<reset>                                                                <cyan>║<reset>\n")
cecho("<cyan>║<reset> <yellow>Sort Commands:<reset>                                                 <cyan>║<reset>\n")
cecho("<cyan>║<reset>   <white>shipdb sort <column><reset>   Sort by: type, name, owner, planet,   <cyan>║<reset>\n")
cecho("<cyan>║<reset>                              dock, or time                     <cyan>║<reset>\n")
cecho("<cyan>║<reset>                                                                <cyan>║<reset>\n")
cecho("<cyan>║<reset> <yellow>Debug Commands:<reset>                                                <cyan>║<reset>\n")
cecho("<cyan>║<reset>   <white>shipdbdebug 1<reset>          Enable debug mode                     <cyan>║<reset>\n")
cecho("<cyan>║<reset>   <white>shipdbdebug 0<reset>          Disable debug mode                    <cyan>║<reset>\n")
cecho("<cyan>║<reset>                                                                <cyan>║<reset>\n")
cecho("<cyan>║<reset> <yellow>Interactive Features:<reset>                                          <cyan>║<reset>\n")
cecho("<cyan>║<reset>   • Click column headers to sort                               <cyan>║<reset>\n")
cecho("<cyan>║<reset>   • Click any field to filter by that value                    <cyan>║<reset>\n")
cecho("<cyan>║<reset>   • Click ship name to view docking history                    <cyan>║<reset>\n")
cecho("<cyan>║<reset>   • Right-click ship name for more options                     <cyan>║<reset>\n")
cecho("<cyan>║<reset>   • Use Ships/History buttons to toggle views                  <cyan>║<reset>\n")
cecho("<cyan>║<reset>   • Use search box to filter in real-time                      <cyan>║<reset>\n")
cecho("<cyan>╚════════════════════════════════════════════════════════════════╝<reset>\n\n")
